name: Deploy Nodejs app to docker hub then remote server

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/node-secret-service:latest

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.REMOTE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "USERNAME=admin" >> /home/${{ vars.REMOTE_USERNAME }}/.env
            echo "PASSWORD=pass1234" >> /home/${{ vars.REMOTE_USERNAME }}/.env
            echo "SECRET_MESSAGE=This is top secret!" >> /home/${{ vars.REMOTE_USERNAME }}/.env
            docker pull ${{ vars.DOCKER_USERNAME }}/node-secret-service:latest
            docker stop node-secret-service || true
            docker rm node-secret-service || true
            docker run -d --name node-secret-service -p 80:3000 \
              --env-file /home/${{ vars.REMOTE_USERNAME }}/.env \
              ${{ vars.DOCKER_USERNAME }}/node-secret-service:latest
